-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create a table for users (profiles) linked to auth.users
-- This table extends the default auth.users table with application-specific fields
CREATE TABLE public.users (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  image TEXT,
  url TEXT,
  "isAdmin" BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create policies for users
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.users FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile" 
ON public.users FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
ON public.users FOR UPDATE USING (auth.uid() = id);

-- Categories Table
CREATE TABLE public.category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.category ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categories are viewable by everyone" ON public.category FOR SELECT USING (true);
-- Only admins should be able to insert/update/delete (add specific policies later if needed)
CREATE POLICY "Authenticated users can create categories" ON public.category FOR INSERT WITH CHECK (auth.role() = 'authenticated'); 
CREATE POLICY "Authenticated users can update categories" ON public.category FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete categories" ON public.category FOR DELETE USING (auth.role() = 'authenticated');


-- Videos Table
CREATE TABLE public.video (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  description TEXT,
  video TEXT, -- URL or path to storage
  url TEXT,   -- Helper URL if needed
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.video ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Videos are viewable by everyone" ON public.video FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage videos" ON public.video FOR ALL USING (auth.role() = 'authenticated');


-- News Table
CREATE TABLE public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" UUID REFERENCES public.users(id) NOT NULL, -- references our public.users (which links to auth.users)
  "catId" BIGINT REFERENCES public.category(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  "subTitle1" TEXT,
  "subDescription1" TEXT,
  "subTitle2" TEXT,
  "subDescription2" TEXT,
  "subTitle3" TEXT,
  "subDescription3" TEXT,
  "subTitle4" TEXT,
  "subDescription4" TEXT,
  "numViews" INTEGER DEFAULT 0,
  "numLike" INTEGER DEFAULT 0,
  image TEXT, -- Main image URL
  url TEXT,
  images TEXT[], -- Array of image URLs
  "imagesUrl" TEXT[], -- Helper array if needed
  video TEXT, -- Video URL
  "videoUrl" TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
CREATE POLICY "News are viewable by everyone" ON public.news FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage news" ON public.news FOR ALL USING (auth.role() = 'authenticated');


-- Comments Table
CREATE TABLE public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "newsId" BIGINT REFERENCES public.news(id) ON DELETE CASCADE NOT NULL,
  description TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  "isActive" BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Comments viewable by everyone" ON public.comments FOR SELECT USING (true);
CREATE POLICY "Anyone can insert comments" ON public.comments FOR INSERT WITH CHECK (true);
CREATE POLICY "Authenticated users can manage comments" ON public.comments FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete comments" ON public.comments FOR DELETE USING (auth.role() = 'authenticated');


-- Storage Buckets Setup (You must create these buckets in Supabase Storage dashboard or via SQL if supported by extensions)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('news-images', 'news-images', true);
-- INSERT INTO storage.buckets (id, name, public) VALUES ('videos', 'videos', true);
-- INSERT INTO storage.buckets (id, name, public) VALUES ('profile-images', 'profile-images', true);

-- Helper function to handle new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the function every time a user is created
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- RPC for incrementing views
CREATE OR REPLACE FUNCTION increment_news_view(row_id BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.news
  SET "numViews" = "numViews" + 1
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

-- RPC for incrementing likes
CREATE OR REPLACE FUNCTION increment_news_like(row_id BIGINT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.news
  SET "numLike" = "numLike" + 1
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

